version: "3.8"
services:
  web:
    image: nginx
    ports:
      - "8082:80"
    restart: always

  db:
    image: mysql:8
    environment:
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - dbdata:/var/lib/mysql

volumes:
  dbdata:

